enum SettingsLegalContent {
	static let privacyPolicy = [
		"Privacy Policy\nLast updated: August 18, 2026",
		"This Privacy Policy applies to the Beacon mobile application, referred to below as Beacon. Beacon is a local-first AI chat application. It does not require an account, and it does not provide cloud AI chat or send your chat content to a third-party AI service.",
		"Information stored on your device\nBeacon stores the following information locally on your device to provide its features:\n- The conversations, prompts, AI responses, and any images you attach, so that chat history and local AI responses can be displayed.\n- Your selected model, downloaded model IDs, onboarding state, notification preference, and app settings.\nBeacon does not upload this locally stored information. You can delete saved chats from Settings.",
		"Local AI processing\nYour prompts, attached images, conversation history, and AI responses are processed on your device by the model you select. They are not sent to Beacon, Hugging Face, Apple, or any other third-party AI service for AI inference, training, or advertising.",
		"Network requests and recipients\nBeacon makes network requests only when you choose to download a model from Hugging Face. These requests do not include your prompts, attached images, AI responses, or chat history.\n- Hugging Face receives the model repository identifier you select and standard network request metadata, including IP address and user agent, when you choose to download a model. Hugging Face uses this information to deliver the selected model under its own privacy practices.\n- The downloaded model is stored on your device and used locally. Choosing a model download is your action to request that transfer.",
		"Third-party services\nHugging Face is a third-party model-hosting service, not a provider of Beacon's chat inference. Beacon does not share personal data with a third-party AI service. Beacon does not sell personal information or use it for cross-app tracking or advertising. Third parties that receive limited request information must protect it under their applicable privacy and security obligations.",
		"Web search\nWeb search is not available in the current release. If Beacon adds a feature that sends a query or other personal data to a third party, Beacon will disclose the data and recipient and request your permission before that data is sent.",
		"Location information\nBeacon does not collect precise real-time location information from your device.",
		"Your choices\nYou can use Beacon's local chat without making a network request for AI inference. You may choose not to download additional models. You can delete saved chats in Settings, remove downloaded models from the model marketplace, or uninstall Beacon using the standard uninstall process.",
		"Children\nBeacon is not intended to knowingly solicit data from or market to children under the age of 13. If you believe a child has provided personal information through the Application, contact us so appropriate action can be taken.",
		"Security\nBeacon is designed to keep local chats and downloaded models on your device. You are responsible for maintaining the security of your device, passcode, Apple ID, and backups. Jailbreaking or modifying your device may compromise the security and reliability of the Application.",
		"Changes\nThis Privacy Policy may be updated from time to time. If a change requires permission before Beacon sends personal data to a third party, Beacon will request that permission before making the transfer.",
		"Contact Us\nIf you have questions about privacy while using Beacon, contact us at semeraco@gmail.com."
	]

	static let terms = [
		"Terms & Conditions\nLast updated: June 26, 2026",
		"These Terms & Conditions apply to the Beacon mobile application, hereby referred to as the Application. By downloading or using the Application, you agree to these terms. Please read them carefully before using Beacon.",
		"License and restrictions\nYou may use the Application for personal use in accordance with these terms. You may not:\n- Copy, modify, or redistribute the Application without permission.\n- Reverse engineer, extract source code, or create derivative versions except where allowed by law.\n- Use Beacon branding, trademarks, or interface assets without permission.",
		"Intellectual property\nThe Application, branding, interface, trademarks, and related intellectual property remain the property of their respective owners. Third-party models, libraries, and services remain governed by their own licenses and terms.",
		"Local-first AI\nBeacon provides local AI chat and model management features. Supported models may run on your device. You are responsible for how you use model outputs and for reviewing important information before relying on it.",
		"AI accuracy\nAI responses may be inaccurate, incomplete, outdated, or unsuitable for your use case. Do not use Beacon as the sole source of truth for:\n- Medical, legal, financial, or safety-critical decisions.\n- Emergency situations.\n- Decisions where incorrect information could cause harm.",
		"Model downloads and third-party services\nBeacon may allow you to download models from third-party services such as Hugging Face. You are responsible for reviewing and complying with the terms that apply to any model you download or use.\n- Models may have their own licenses.\n- Models may have acceptable use policies.\n- Some models may restrict commercial, redistributed, or sensitive use.",
		"Model downloads\nDownloading an optional model requires an internet connection and contacts Hugging Face. Chat inference does not require Beacon backend infrastructure.",
		"Connectivity and charges\nSome functions require Wi-Fi or mobile data. You are responsible for any charges related to use of the Application. This includes:\n- Mobile data usage.\n- Roaming charges.\n- Third-party network or service charges.\nIf you are not the bill payer for the device, you confirm that you have permission from the bill payer to use the Application.",
		"Device responsibility\nYou are responsible for keeping your device charged, secure, and compatible with the Application. Jailbreaking, rooting, or modifying your device may cause Beacon to work incorrectly or not at all.",
		"Updates and availability\nBeacon may be updated, changed, suspended, or discontinued at any time.\n- Updates may be required to continue using the Application.\n- Features may change or be removed.\n- Compatibility with every device or operating system version is not guaranteed.",
		"Termination\nWe may stop providing the Application or terminate access to features at any time. Upon termination, the rights granted to you under these terms will end, and you must stop using the Application if required.",
		"Limitation of liability\nTo the fullest extent permitted by law, Beacon is provided as is and without warranties of any kind. We are not liable for losses, direct or indirect, arising from your use of the Application, model outputs, downloaded models, web search results, third-party services, or inability to access the Application.",
		"Changes to these Terms & Conditions\nThese Terms & Conditions may be updated from time to time. You are advised to review them regularly. Continued use of the Application after changes means you accept the updated terms.",
		"Contact Us\nIf you have questions or suggestions about these Terms & Conditions, contact us at semeraco@gmail.com."
	]
}
