enum SettingsLegalContent {
	static let privacyPolicy = [
		"Privacy Policy\nLast updated: August 5, 2026",
		"This Privacy Policy applies to the Semera mobile application, referred to below as Semera. Semera is a local-first AI chat application. It does not require an account, and it does not provide cloud AI chat or send your chat content to a third-party AI service.",
		"Information stored on your device\nSemera stores the following information locally on your device to provide its features:\n- The conversations, prompts, AI responses, and any images you attach, so that chat history and local AI responses can be displayed.\n- Optional saved memories you create, so local chat can use them.\n- Your selected model, downloaded model IDs, onboarding state, notification preference, and app settings.\nSemera does not upload this locally stored information. You can delete saved chats and memories from Settings.",
		"Local AI processing\nYour prompts, attached images, saved memories, and AI responses are processed on your device by the model you select. They are not sent to Semera, Hugging Face, Apple, or any other third-party AI service for AI inference, training, or advertising.",
		"Network requests and recipients\nSemera makes limited network requests only to provide the model catalog and to download a model you choose. These requests do not include your prompts, attached images, saved memories, AI responses, or chat history.\n- Semera's model catalog service receives the app version, device and network request metadata such as IP address and user agent, and the request needed to return the list of available models. Semera uses this information only to operate, secure, and troubleshoot the catalog service.\n- Hugging Face receives the model repository identifier you select and standard network request metadata, including IP address and user agent, when you choose to download a model. Hugging Face uses this information to deliver the selected model under its own privacy practices.\n- The downloaded model is stored on your device and used locally. Choosing a model download is your action to request that transfer.",
		"Third-party services\nHugging Face is a third-party model-hosting service, not a provider of Semera's chat inference. Semera does not share personal data with a third-party AI service. Semera does not sell personal information or use it for cross-app tracking or advertising. Third parties that receive limited request information must protect it under their applicable privacy and security obligations.",
		"Web search\nWeb search is not available in the current release. If Semera adds a feature that sends a query or other personal data to a third party, Semera will disclose the data and recipient and request your permission before that data is sent.",
		"Location information\nSemera does not collect precise real-time location information from your device.",
		"Your choices\nYou can use Semera's local chat without making a network request for AI inference. You may choose not to download additional models. You can delete saved chats and memories in Settings, remove downloaded models from the model marketplace, or uninstall Semera using the standard uninstall process.",
		"Children\nSemera is not intended to knowingly solicit data from or market to children under the age of 13. If you believe a child has provided personal information through the Application, contact us so appropriate action can be taken.",
		"Security\nSemera is designed to keep local chats and downloaded models on your device. You are responsible for maintaining the security of your device, passcode, Apple ID, and backups. Jailbreaking or modifying your device may compromise the security and reliability of the Application.",
		"Changes\nThis Privacy Policy may be updated from time to time. If a change requires permission before Semera sends personal data to a third party, Semera will request that permission before making the transfer.",
		"Contact Us\nIf you have questions about privacy while using Semera, contact us at semeraco@gmail.com."
	]

	static let terms = [
		"Terms & Conditions\nLast updated: June 26, 2026",
		"These Terms & Conditions apply to the Semera mobile application, hereby referred to as the Application. By downloading or using the Application, you agree to these terms. Please read them carefully before using Semera.",
		"License and restrictions\nYou may use the Application for personal use in accordance with these terms. You may not:\n- Copy, modify, or redistribute the Application without permission.\n- Reverse engineer, extract source code, or create derivative versions except where allowed by law.\n- Use Semera branding, trademarks, or interface assets without permission.",
		"Intellectual property\nThe Application, branding, interface, trademarks, and related intellectual property remain the property of their respective owners. Third-party models, libraries, and services remain governed by their own licenses and terms.",
		"Local-first AI\nSemera provides local AI chat and model management features. Supported models may run on your device. You are responsible for how you use model outputs and for reviewing important information before relying on it.",
		"AI accuracy\nAI responses may be inaccurate, incomplete, outdated, or unsuitable for your use case. Do not use Semera as the sole source of truth for:\n- Medical, legal, financial, or safety-critical decisions.\n- Emergency situations.\n- Decisions where incorrect information could cause harm.",
		"Model downloads and third-party services\nSemera may allow you to download models from third-party services such as Hugging Face. You are responsible for reviewing and complying with the terms that apply to any model you download or use.\n- Models may have their own licenses.\n- Models may have acceptable use policies.\n- Some models may restrict commercial, redistributed, or sensitive use.",
		"Optional web search\nSome features may require an internet connection, including optional web search and model downloads. Web search sends the search query to Semera backend infrastructure so current information can be retrieved. Semera is not responsible for third-party web content or for decisions you make based on that content.",
		"Connectivity and charges\nSome functions require Wi-Fi or mobile data. You are responsible for any charges related to use of the Application. This includes:\n- Mobile data usage.\n- Roaming charges.\n- Third-party network or service charges.\nIf you are not the bill payer for the device, you confirm that you have permission from the bill payer to use the Application.",
		"Device responsibility\nYou are responsible for keeping your device charged, secure, and compatible with the Application. Jailbreaking, rooting, or modifying your device may cause Semera to work incorrectly or not at all.",
		"Updates and availability\nSemera may be updated, changed, suspended, or discontinued at any time.\n- Updates may be required to continue using the Application.\n- Features may change or be removed.\n- Compatibility with every device or operating system version is not guaranteed.",
		"Termination\nWe may stop providing the Application or terminate access to features at any time. Upon termination, the rights granted to you under these terms will end, and you must stop using the Application if required.",
		"Limitation of liability\nTo the fullest extent permitted by law, Semera is provided as is and without warranties of any kind. We are not liable for losses, direct or indirect, arising from your use of the Application, model outputs, downloaded models, web search results, third-party services, or inability to access the Application.",
		"Changes to these Terms & Conditions\nThese Terms & Conditions may be updated from time to time. You are advised to review them regularly. Continued use of the Application after changes means you accept the updated terms.",
		"Contact Us\nIf you have questions or suggestions about these Terms & Conditions, contact us at semeraco@gmail.com."
	]
}
